export const presentes = [
  {
    id: "baba-eletronica",
    categoria: "quarto",
    nome: "Babá Eletrônica",
    link: "https://s.shopee.com.br/AKYqseebwL",
  },
  {
    id: "ruido-branco",
    categoria: "quarto",
    nome: "Ruído Branco",
    link: "https://s.shopee.com.br/5fn1JrSDxR",
  
  },
  {
    id: "carrinho",
    categoria: "passeio",
    nome: "Carrinho Moisés + Bebê Conforto",
    link: "https://s.shopee.com.br/8pk35OJB4V",
  },
  {
    id: "lixeira",
    categoria: "quarto",
    nome: "Lixeira Antiodor",
    link: "https://s.shopee.com.br/8V7ChaiFJg",
  },
  {
    id: "colmeia",
    categoria: "quarto",
    nome: "Kit Colmeia Organizadora",
    link: "https://s.shopee.com.br/18eaRtgf8",
  },
  {
    id: "cabides",
    categoria: "quarto",
    nome: "Organizador de Cabides",
    link: "https://s.shopee.com.br/5LAAwPDoWP",
    quantidadeDesejada: 5,
  },
  {
    id: "kit-higiene",
    categoria: "higiene",
    nome: "Kit Higiene",
    link: "https://s.shopee.com.br/2BD9AqsXEw",
    
  },
  {
    id: "cesto",
    categoria: "quarto",
    nome: "Cesto Organizador",
    link: "https://s.shopee.com.br/18ebPVRzE",
  },
  {
    id: "body-curta",
    categoria: "roupinhas",
    nome: "Body Manga Curta",
    link: "https://s.shopee.com.br/9AMtU8DZp2",
  },
  {
    id: "kit-body",
    categoria: "roupinhas",
    nome: "Kit Body",
    link: "https://s.shopee.com.br/6ffYVbvmAk",
  },
{
  id: "kit-tapa-fralda",
  categoria: "roupinhas",
  nome: "Kit Tapa Fralda",
  link: "https://s.shopee.com.br/40enKMNc8M",
},
{
  id: "lacinhos",
  categoria: "acessorios",
  nome: "Lacinhos",
  link: "https://s.shopee.com.br/70IOtndVmT",
},
{
  id: "meias",
  categoria: "acessorios",
  nome: "Meias",
  link: "https://s.shopee.com.br/8V7CiehqY8",
},
{
  id: "kit-meia-luva",
  categoria: "acessorios",
  nome: "Kit Meia e Luva",
  link: "https://s.shopee.com.br/5fn1LbIphS",
},
{
  id: "kit-lacos",
  categoria: "acessorios",
  nome: "Kit Laços",
  link: "https://s.shopee.com.br/2g9Pm9uCof",
},
{
  id: "sapatinho-1",
  categoria: "calcados",
  nome: "Sapatinho",
  link: "https://s.shopee.com.br/7KvFKmF1Ry",
},
{
  id: "calcado-baby",
  categoria: "calcados",
  nome: "Calçado Baby",
  link: "https://s.shopee.com.br/20tizAHUAi",
},
{
  id: "sapatilha-dourada",
  categoria: "calcados",
  nome: "Sapatilha Baby Dourada",
  link: "https://s.shopee.com.br/60PrkZREqh",
},
{
  id: "sapatinho-2",
  categoria: "calcados",
  nome: "Sapatinho Rosa",
  link: "https://s.shopee.com.br/9KgJimujSu",
},
{
  id: "tricot-branco",
  categoria: "calcados",
  nome: "Sapatinho de Tricô Branco",
  link: "https://s.shopee.com.br/5q6RYPXFA2",
},
{
  id: "tricot-rosa",
  categoria: "calcados",
  nome: "Sapatinho de Tricô Rosa",
  link: "https://s.shopee.com.br/5q6RYPXFA2",
},
{
  id: "sapatinho-flores",
  categoria: "calcados",
  nome: "Sapatinho Rosa com Flores",
  link: "https://s.shopee.com.br/W4vCmUKt4",
},
{
  id: "bomba-leite",
  categoria: "amamentacao",
  nome: "Bomba de Leite",
  link: "https://s.shopee.com.br/AAFQin1qO3",
},
{
  id: "rosquinha-mama",
  categoria: "amamentacao",
  nome: "Rosquinha de Amamentação",
  link: "https://s.shopee.com.br/4fuUAoSHTt",
},
{
  id: "touca-luva",
  categoria: "acessorios",
  nome: "Touca e Luva Personalizada",
  link: "https://s.shopee.com.br/5fn1MhRf78",
},
{
  id: "vestido-baby",
  categoria: "roupinhas",
  nome: "Vestido Baby",
  link: "https://s.shopee.com.br/4qDuNUzFl7",
},
{
  id: "body-flor",
  categoria: "roupinhas",
  nome: "Body Baby Flor",
  link: "https://s.shopee.com.br/40enOA2wMg",
},
{
  id: "roupa-floral",
  categoria: "roupinhas",
  nome: "Roupa Floral",
  link: "https://s.shopee.com.br/3ViWyjCDj5",
},
{

  id: "pomada-assadura",
  categoria: "higiene",
  nome: "Pomada de Assadura (Mustela, Desitin ou Bepantol)",
  link: "",
  quantidadeDesejada: 10,

},
{
  id: "lenco-umedecido",
  categoria: "higiene",
  nome: "Lenço Umedecido (Johnson's)",
  link: "",
  quantidadeDesejada: 12,
},
{
  id: "algodao",
  categoria: "higiene",
  nome: "Algodão",
  link: "",
},
{
  id: "alcool-70",
  categoria: "higiene",
  nome: "Álcool 70%",
  link: "",
},
{
  id: "hidratante",
  categoria: "higiene",
  nome: "Hidratante Corporal (Mamãe e Bebê Natura ou Mustela)",
  link: "",
  quantidadeDesejada: 5,
},
{
  id: "sabonete",
  categoria: "higiene",
  nome: "Sabonete (Johnson's ou Mustela)",
  link: "",
  quantidadeDesejada: 6,
},
{
  id: "cotonete",
  categoria: "higiene",
  nome: "Cotonete",
  link: "",
},
{
  id: "perfume",
  categoria: "higiene",
  nome: "Perfume Mamãe e Bebê Natura",
  link: "",
  quantidadeDesejada: 5,
},
{
  id: "shampoo",
  categoria: "higiene",
  nome: "Shampoo Neutro (Johnson's, Mustela ou Mamãe e Bebê Natura)",
  link: "",
  quantidadeDesejada: 5,
},

{
  id: "macacao-fofo",
  categoria: "roupinhas",
  nome: "Macacão Fofo",
  link: "",
  quantidadeDesejada: 10,
}
];
